### ISSUE TITLE
CRUD implementation

### ISSUE THREAD

**Issue by finoptimal-dev** [simonv3/quickbooks-python#5]
Simon,

I have finally figured out some creating, updating, and deleting tools. I will add those to my repository now. Let me know if you want me to do a pull request.

Thanks,

HaPsantran

**Comment by simonv3** [comment]
Hey HaPsantran, finally getting back to this! Is this more up to date than what I just merged?

**Comment by finoptimal-dev** [comment]
It's the newest. Mine could definitely have some bugs still, but it does create the transactions and I've used it extensively for that purpose. I'm still using a different tool to get access tokens, however, so if you could share an example of how your module does it, that would be helpful.

Thanks again!
